
package sd.tp1.server.replication.backdoor.client.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SOAPReplicationServerBackdoorService", targetNamespace = "http://backdoor.replication.server.tp1.sd/", wsdlLocation = "http://localhost:8081/replication?wsdl")
public class SOAPReplicationServerBackdoorService
    extends Service
{

    private final static URL SOAPREPLICATIONSERVERBACKDOORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPREPLICATIONSERVERBACKDOORSERVICE_EXCEPTION;
    private final static QName SOAPREPLICATIONSERVERBACKDOORSERVICE_QNAME = new QName("http://backdoor.replication.server.tp1.sd/", "SOAPReplicationServerBackdoorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/replication?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPREPLICATIONSERVERBACKDOORSERVICE_WSDL_LOCATION = url;
        SOAPREPLICATIONSERVERBACKDOORSERVICE_EXCEPTION = e;
    }

    public SOAPReplicationServerBackdoorService() {
        super(__getWsdlLocation(), SOAPREPLICATIONSERVERBACKDOORSERVICE_QNAME);
    }

    public SOAPReplicationServerBackdoorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPREPLICATIONSERVERBACKDOORSERVICE_QNAME, features);
    }

    public SOAPReplicationServerBackdoorService(URL wsdlLocation) {
        super(wsdlLocation, SOAPREPLICATIONSERVERBACKDOORSERVICE_QNAME);
    }

    public SOAPReplicationServerBackdoorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPREPLICATIONSERVERBACKDOORSERVICE_QNAME, features);
    }

    public SOAPReplicationServerBackdoorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPReplicationServerBackdoorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SOAPReplicationServerBackdoor
     */
    @WebEndpoint(name = "SOAPReplicationServerBackdoorPort")
    public SOAPReplicationServerBackdoor getSOAPReplicationServerBackdoorPort() {
        return super.getPort(new QName("http://backdoor.replication.server.tp1.sd/", "SOAPReplicationServerBackdoorPort"), SOAPReplicationServerBackdoor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPReplicationServerBackdoor
     */
    @WebEndpoint(name = "SOAPReplicationServerBackdoorPort")
    public SOAPReplicationServerBackdoor getSOAPReplicationServerBackdoorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://backdoor.replication.server.tp1.sd/", "SOAPReplicationServerBackdoorPort"), SOAPReplicationServerBackdoor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPREPLICATIONSERVERBACKDOORSERVICE_EXCEPTION!= null) {
            throw SOAPREPLICATIONSERVERBACKDOORSERVICE_EXCEPTION;
        }
        return SOAPREPLICATIONSERVERBACKDOORSERVICE_WSDL_LOCATION;
    }

}
