
package sd.tp1.client.cloud.soap.stubs;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapServer", targetNamespace = "http://soap.server.tp1.sd/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<sd.tp1.client.cloud.soap.stubs.SharedPicture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListOfPictures", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.GetListOfPictures")
    @ResponseWrapper(localName = "getListOfPicturesResponse", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.GetListOfPicturesResponse")
    @Action(input = "http://soap.server.tp1.sd/SoapServer/getListOfPicturesRequest", output = "http://soap.server.tp1.sd/SoapServer/getListOfPicturesResponse")
    public List<SharedPicture> getListOfPictures(
        @WebParam(name = "arg0", targetNamespace = "")
        SharedAlbum arg0);

    /**
     * 
     * @return
     *     returns java.util.List<sd.tp1.client.cloud.soap.stubs.SharedAlbum>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listOfAlbums", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.ListOfAlbums")
    @ResponseWrapper(localName = "listOfAlbumsResponse", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.ListOfAlbumsResponse")
    @Action(input = "http://soap.server.tp1.sd/SoapServer/listOfAlbumsRequest", output = "http://soap.server.tp1.sd/SoapServer/listOfAlbumsResponse")
    public List<SharedAlbum> listOfAlbums();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPictureData", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.GetPictureData")
    @ResponseWrapper(localName = "getPictureDataResponse", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.GetPictureDataResponse")
    @Action(input = "http://soap.server.tp1.sd/SoapServer/getPictureDataRequest", output = "http://soap.server.tp1.sd/SoapServer/getPictureDataResponse")
    public byte[] getPictureData(
        @WebParam(name = "arg0", targetNamespace = "")
        SharedAlbum arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SharedPicture arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createAlbum", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.CreateAlbum")
    @ResponseWrapper(localName = "createAlbumResponse", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.CreateAlbumResponse")
    @Action(input = "http://soap.server.tp1.sd/SoapServer/createAlbumRequest", output = "http://soap.server.tp1.sd/SoapServer/createAlbumResponse")
    public void createAlbum(
        @WebParam(name = "arg0", targetNamespace = "")
        SharedAlbum arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "uploadPicture", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.UploadPicture")
    @ResponseWrapper(localName = "uploadPictureResponse", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.UploadPictureResponse")
    @Action(input = "http://soap.server.tp1.sd/SoapServer/uploadPictureRequest", output = "http://soap.server.tp1.sd/SoapServer/uploadPictureResponse")
    public void uploadPicture(
        @WebParam(name = "arg0", targetNamespace = "")
        SharedAlbum arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SharedPicture arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAlbum", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.DeleteAlbum")
    @ResponseWrapper(localName = "deleteAlbumResponse", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.DeleteAlbumResponse")
    @Action(input = "http://soap.server.tp1.sd/SoapServer/deleteAlbumRequest", output = "http://soap.server.tp1.sd/SoapServer/deleteAlbumResponse")
    public void deleteAlbum(
        @WebParam(name = "arg0", targetNamespace = "")
        SharedAlbum arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePicture", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.DeletePicture")
    @ResponseWrapper(localName = "deletePictureResponse", targetNamespace = "http://soap.server.tp1.sd/", className = "sd.tp1.client.cloud.soap.stubs.DeletePictureResponse")
    @Action(input = "http://soap.server.tp1.sd/SoapServer/deletePictureRequest", output = "http://soap.server.tp1.sd/SoapServer/deletePictureResponse")
    public boolean deletePicture(
        @WebParam(name = "arg0", targetNamespace = "")
        SharedAlbum arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SharedPicture arg1);

}
